# Generated by Django 5.2.12 on 2026-03-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicaback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='snaptrade_user_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='snaptrade_user_secret',
        ),
    ]
