# Generated by Django 5.2.12 on 2026-03-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicaback', '0002_remove_profile_snaptrade_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(default=0, max_length=100)),
                ('genre', models.CharField(default=0, max_length=15)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
