# Generated by Django 5.2.12 on 2026-03-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicaback', '0003_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artist_name',
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='title',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(max_length=255),
        ),
    ]
